# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_clone_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
