# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello_clone_app', '0002_card_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='lists',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trello_clone_app.List'),
        ),
        migrations.AlterField(
            model_name='list',
            name='cards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trello_clone_app.Card'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='boards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trello_clone_app.Board'),
        ),
    ]
