# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello_clone_app', '0003_auto_20170331_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='lists',
        ),
        migrations.RemoveField(
            model_name='list',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='boards',
        ),
        migrations.AddField(
            model_name='board',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trello_clone_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='card',
            name='cards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trello_clone_app.List'),
        ),
        migrations.AddField(
            model_name='list',
            name='boards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trello_clone_app.Board'),
        ),
    ]
